[workspace]
authors = ["honkatsu <nyanziba@example.com>"]
channels = ["robostack-humble", "conda-forge"]
name = "ROS2-Suspention"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
ros-humble-desktop = ">=0.10.0,<0.11"
ros-humble-turtlesim = ">=1.4.2,<2"
